NEI<-readRDS("./Source_Classification_Code.rds")
SCC<-readRDS("./summarySCC_PM25.rds")
s<-split(NEI,NEI$year)
a<-rbind(mean(s$'1999'[,4]),mean(s$'2002'[,4]),mean(s$'2005'[,4]),mean(s$'2008'[,4]))
b<-cbind(1999,2002,2005,2008)
c<-cbind(b,a)
output<-data.frame(c)
names(output)<-c("year","Emissions")
with(output, plot(year, Emissions, main="Total emissions vs. year",xlab = "year", ylab = "Total emissions", col = "1", type='o'))
dev.copy(png, file = "plot1.png")
dev.off()